name: Deploy Terraform to UAT

run-name: Deploy Terraform to UAT from ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      confirm_uat_deployment:
        description: Confirm an intentional Terraform deployment to UAT.
        required: true
        default: false
        type: boolean

permissions: {}

jobs:
  deploy-uat:
    name: Deploy Terraform to UAT
    if: inputs.confirm_uat_deployment
    permissions:
      contents: read
      id-token: write
    uses: joshcazalas/money-on-record/.github/workflows/reusable-terraform-deploy.yml@main
    with:
      environment: uat
